# model_family: llama2-7b
# model_family: phi
model_family: llama3-3b

LoRA:
  r: 0
  alpha: 32
  dropout: 0.05

data_path: locuslab/TOFU
split: full
batch_size: 4
gradient_accumulation_steps: 4
num_epochs: 5
lr: 1e-5
seed: 42
run_index: 1
# save_dir: /data/XZhou/unlearning/results/train/final_ft_noLORA_5_epochs_inst_lr${lr}_${model_family}_${split}_seed${seed}_${run_index}
save_dir: /data/XZhou/unlearning/results/train/final_ft_noLORA_5_epochs_inst_lr${lr}_${model_family}_${split}_seed${seed}_${run_index}
weight_decay: 0.01